[package]
name = "lab-rust"
version = "0.1.0"
edition = "2018" # or "2021"
authors = ["JamesBond <introbond.dev@gmail.com>"]

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
